### ISSUE TITLE
Passer en responsive

### ISSUE THREAD

**Issue by Machou** [AmauryCarrade/OranjeProxy#27]
Hello

Je vais travailler sur le responsive, car j'utilise souvent mon proxy sur mobile, hélas il n'est pas responsive et ce n'est pas très beau.

Intéressé ? ;)

**Comment by AmauryCarrade** [comment]
Je suis ouvert à tout PR qu'on me propose :) .

**Comment by Machou** [comment]
J'ai pensé à un truc comme ça : https://i.imgur.com/7EZ1Uxa.png
